---
- name: Configure personal Linux systems
  hosts: localhost
  become: true
  become_user: ansible
  tasks:
    - name: Setup dotfiles and configs
      ansible.builtin.include_role:
        name: dotfiles
