#!/bin/bash
#
# Script used to batch rename image files in a directory

Help()
{
    # Display help
    echo "rename - Batch rename image files in directory"
    echo
    echo "Syntax: rename <new_name> [starting_idx]"
    echo
    echo "positional arguments:"
    echo "new_name      New name for the image files"
    echo "starting_idx  Starting index to for renamed files, default = 1"
    echo
}

name="$1"
idx="$2"

if [[ ! "$name" ]]; then
    echo "No name entered. Help: "
    echo
    Help
    exit 1
fi

if [[ ! "$idx" ]]; then
    idx=1
fi

mkdir -p "$name"

for file in *.jpg *.JPG *.png *.PNG *.jpg *.jpeg *.JPEG *.webp *.WEBP; do
    
    if [ ! -f "$file" ]; then
        continue
    fi

    new_name="${name}/${name}_${idx}.jpg"

    if [[ $file == *.png || $file == *.PNG || $file == *.webp || $file == *.WEBP ]]; then
        convert "$file" "$new_name"
        rm "$file"
    else
        mv "$file" "$new_name"
    fi



    idx=$((${idx} + 1))
done


