#!/bin/bash

usage() {
    echo "Usage: $0 [-s number]"
    exit 1
}

while getopts ":s:" opt; do
    case ${opt} in
        s )
            limit=$OPTARG
            ;;
        \? )
            usage
            ;;
    esac
done

shift $((OPTIND - 1))

if [ ! -z "limit" ]; then
    if ! [[ "$limit" =~ ^[0-9]+$ ]]; then
        echo "Error: the -s argument must be a number."
        exit 1
    fi
fi


for file in *.mp4; do
    duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$file")
    if (( $(echo "$duration > $limit" | bc -l) )); then
        echo "$file"
    fi
done
