---
- name: Update dotfiles
  hosts: localhost
  gather_facts: true
  become: false
  vars_files:
    - vars/test.yml
    # - vars/dotfiles.yml
  # vars:
  #   dotfiles_dir: "{{ ansible_user_dir }}/.dotfiles/"
  #   config_dir: "{{ ansible_user_dir }}/.config/"
  tasks:
    # - name: Make sure dotfiles git repo is present
    #   ansible.builtin.git:
    #     repo: https://github.com/pcs03/dotfiles.git
    #     dest: ~/.dotfiles
    #     version: main
    #     update: true
    #
    # - name: Print facts
    #   ansible.builtin.debug:
    #     msg: >-
    #       FQDN {{ ansible_fqdn }}
    #       IP {{ ansible_default_ipv4.address }}
    #       dotfiles {{ dotfiles }}
    #
    # - name: Symlink dotfiles
    #   ansible.builtin.debug:
    #     var: "{{ item }}"
    #     # src: "{{ dotfiles_dir }}/dot/{{ item }}"
    #     # dest: "{{ ansible_user_dir }}/{{ item }}"
    #     # state: link
    #   loop: "{{ dotfiles }}"
    # - name: Install base packages
    #   ansible.builtin.

    - name: Print
      ansible.builtin.debug:
        var: test_var

    - name: Ensure AUR and packages are installed for Arch Linux
      when: ansible_facts['distribution'] == "Archlinux"
      block:
        - name: Ensure aur_builder user for AUR is present
          become: true
          ansible.builtin.user:
            name: aur_builder
            create_home: true
            group: wheel

        - name: Ensure aur_builder user has sudo access
          become: true
          ansible.builtin.lineinfile:
            path: /etc/sudoers.d/aur_builder
            line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
            create: true
            mode: '0644'
            validate: 'visudo -cf %s'

        - name: Ensure yay is installed
          kewlfft.aur.aur:
            name: yay
            use: makepkg
            state: present
          become: true
          become_user: aur_builder

        - name: Print packages
          ansible.builtin.debug:
            msg: "{{ packages[ansible_facts['distribution']]['base'] }}"

        # - name: Ensure base packages are installed
        #   kewlfft.aur.aur:
        #     use: yay
        #     name: "{{ packages[ansible_facts['distribution']][base] }}"
        #     state: latest
