---
- name:  Link a config directory to XDG_CONFIG_HOME
  hosts: localhost
  become: false

  vars:
    config_directories:
      # Config directories that will be linked to XDG_CONFIG_HOME
      # If a directory already exists there, it will be deleted
      # Comment out what should not be symlinked
      # Desktop/Server
      - nvim
      - tmux
      - zsh
      - kitty
      # Tiling Window Manager:
      - hypr
      - swaylock
      - waybar
      - wlogout
      - wofi
      # other desktop packages:
      - zathura
    dotfiles:
      # Dotfiles that will be placed in HOME
      # If the dotfile already exists, it will be deleted
      # Comment out what should not be symlinked
      # TODO: .ssh dir should not be entirely copied, only config in it should
      - .ssh
      - .bashrc
      - .bash_profile
      - .bash_completion
      - .gitconfig
      - .ideavimrc
      - .vimrc
      - .zshenv

  tasks:
    - name: Print out ansible facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print out the distribution
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: "Print ansible env HOME"
      ansible.builtin.debug:
        msg: "{{ ansible_env.HOME }}"

    - name: "Print ansible env XDG_CONFIG_HOME"
      ansible.builtin.debug:
        msg: "{{ ansible_env.XDG_CONFIG_HOME }}"

    - name: List all config directories
      block:
        - name: Print 1
          ansible.builtin.debug:
            msg: "Print1: {{ item }}"
        - name: Print 2
          ansible.builtin.debug:
            msg: "Print2: {{ item }}"
      with_items: "{{ config_directories }}"



      # - name: Make sure dotfiles git repo is present
      #   ansible.builtin.git:
      #     repo: https://github.com/pcs03/dotfiles.git
      #     dest: ~/.dotfiles
      #     version: main
      #     update: true
